### ISSUE TITLE
Can't run the example - ENAMETOOLONG

### ISSUE THREAD

**Issue by meekrosoft** [Sewdn/meteor-twitter-api#4]
I am trying to run the example on my mac, but it looks like a path is incorrect because of some kind of recursion.  Here is the error message I receive:

```
Mike-Longs-MacBook-Air:basic mike$ mrt

Stand back while Meteorite does its thing

Done installing smart packages

Ok, everything's ready. Here comes Meteor!

[[[[[ ~/tmp/meteor-twitter-api/examples/basic ]]]]]

Running on: http://localhost:3000/
No dependency info in bundle. Filesystem monitoring disabled.
Errors prevented startup:
Exception while bundling application:
Error: ENAMETOOLONG, name too long '/Users/mike/tmp/meteor-twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/packages/twitter-api/examples/basic/basic.css'
    at Object.fs.statSync (fs.js:524:18)
    at Object.module.exports.file_list_sync (/Users/mike/.meteorite/meteors/meteor/meteor/4d98d8cb4e5a95e9e98953f44c872c9332a042a3/app/lib/files.js:83:20)
    at module.exports.file_list_sync (/Users/mike/.meteorite/meteors/meteor/meteor/4d98d8cb4e5a95e9e98953f44c872c9332a042a3/app/lib/files.js:87:32)
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/mike/.meteorite/meteors/meteor/meteor/4d98d8cb4e5a95e9e98953f44c872c9332a042a3/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.module.exports.file_list_sync (/Users/mike/.meteorite/meteors/meteor/meteor/4d98d8cb4e5a95e9e98953f44c872c9332a042a3/app/lib/files.js:86:9)
    at module.exports.file_list_sync (/Users/mike/.meteorite/meteors/meteor/meteor/4d98d8cb4e5a95e9e98953f44c872c9332a042a3/app/lib/files.js:87:32)
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/mike/.meteorite/meteors/meteor/meteor/4d98d8cb4e5a95e9e98953f44c872c9332a042a3/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.module.exports.file_list_sync (/Users/mike/.meteorite/meteors/meteor/meteor/4d98d8cb4e5a95e9e98953f44c872c9332a042a3/app/lib/files.js:86:9)

Please fix the problem and restart.
```

**Comment by thom801** [comment]
I'm also having this problem. Gonna look into it. I think there are some problems with permissions on some files as well. May have something to do with it.

**Comment by northcoders-chris** [comment]
ReferenceError: Twitter is not defined
W20140703-11:54:19.175(1)? (STDERR)     at app/basic.js:13:21
